### ISSUE TITLE
Question: Return all tasks, in every queue, including other users

### ISSUE THREAD

**Issue by kierenalt255** [wandss/FileNetPEAPI#1]
Hello
Great Repository, thanks very much for sharing.
I cant find in the IBM literature how to return all tasks, in every queue, including other users "Inbox", do you know to do it with P8BPMREST ?

queryFlags=1 only returns locked and unlocked work items, but not work items in other users own Inbox queue...

I know WorkplaceXT can list all tasks.

Any help or guidance would be appreciated

Thanks, regards, Kieren.

**Comment by wandss** [comment]
Hello Kieren,
Thanks for the complements, is really good to know that this repository is been helpful.

About your question, as far as I concern and also read until now, I believe that is not possible to retrieve all tasks with P8BMPREST. Since we are authenticating the user, only "user permitted (related)" tasks (work items) or queues are possible to fetch.

Like you, I'm still stuck here using Process Administrator over WorkplaceXT to access work items from other users. This is probably a limitation with the REST API.

If I ever get to confirm this in any documentation, I'll be glad to share.

Best regards,

Wanderley
